### ISSUE TITLE
IMPORTANT! Security Vulnerability Detected in your Repository

### ISSUE THREAD

**Issue by graosssaQnrdra** [ovosimpatico/CLI-TikTok#6]
Hey there!

We have detected a security vulnerability in your repository. Please contact us at [REDACTED BY @ovosimpatico] to get more information on how to fix this issue.

Best regards,
Github Security Team

**Comment by ovosimpatico** [comment]
Do you really think I'm stupid? This is a scam, and you'll be reported to Github and Cloudflare, which you use for your domains.

For users that may find this: the website that was linked above tricked users into downloading a malicious software using a power shell script, and is not Github support.
